const router = require('express').Router();
const PDFDocument = require('pdfkit');
const Bill = require('../models/Bill');
const Customer = require('../models/Customer');
const { auth, adminOnly } = require('../middleware/auth');
const { sendInvoiceEmail } = require('../utils/emailHelper');

// GET /api/bills
router.get('/', auth, async (req, res) => {
  try {
    const { status, customerId, startDate, endDate, page = 1, limit = 20 } = req.query;
    const query = {};
    if (status) query.status = status;
    if (customerId) query.customerId = customerId;
    if (startDate || endDate) {
      query.issueDate = {};
      if (startDate) query.issueDate.$gte = new Date(startDate);
      if (endDate) {
        const end = new Date(endDate);
        end.setHours(23, 59, 59, 999);
        query.issueDate.$lte = end;
      }
    }
    // If customer role, only show their bills
    if (req.user.role === 'customer') {
      const cust = await Customer.findOne({ email: req.user.email });
      if (cust) query.customerId = cust._id;
      else return res.json({ bills: [], total: 0 });
    }

    const bills = await Bill.find(query)
      .populate('customerId', 'name email customerId')
      .sort({ createdAt: -1 })
      .skip((page - 1) * limit)
      .limit(Number(limit));
    const total = await Bill.countDocuments(query);
    const allBills = await Bill.find(query);
    const summary = {
      totalAmount: allBills.reduce((s, b) => s + b.totalAmount, 0),
      paidAmount: allBills.reduce((s, b) => s + b.paidAmount, 0),
      pendingAmount: allBills.reduce((s, b) => s + b.balanceDue, 0),
      overdueCount: allBills.filter(b => b.status === 'overdue').length
    };
    res.json({ bills, total, page: Number(page), pages: Math.ceil(total / limit), summary });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// POST /api/bills/generate
router.post('/generate', auth, adminOnly, async (req, res) => {
  try {
    const { customerId, items, billingPeriodStart, billingPeriodEnd, dueDate, notes } = req.body;
    const customer = await Customer.findById(customerId);
    if (!customer) return res.status(404).json({ error: 'Customer not found' });

    const billNumber = await Bill.generateBillNumber();
    const invoiceNumber = await Bill.generateInvoiceNumber();
    let subtotal = 0, totalTax = 0;
    const billItems = items.map(item => {
      const amount = item.quantity * item.unitPrice;
      const taxAmount = (amount * (item.taxRate || 18)) / 100;
      subtotal += amount;
      totalTax += taxAmount;
      return { ...item, amount, taxAmount };
    });
    const totalAmount = subtotal + totalTax;

    // Calculate grace date (2 days after due date)
    const dueDateObj = new Date(dueDate);
    const graceDate = new Date(dueDateObj);
    graceDate.setDate(graceDate.getDate() + 2);

    const bill = new Bill({
      billNumber, invoiceNumber,
      customerId: customer._id,
      customerName: customer.name, customerEmail: customer.email,
      customerPhone: customer.phone,
      customerAddress: `${customer.address?.street || ''}, ${customer.address?.city || ''}, ${customer.address?.state || ''} - ${customer.address?.zipCode || ''}`,
      customerGstin: customer.gstin,
      billingPeriodStart: new Date(billingPeriodStart),
      billingPeriodEnd: new Date(billingPeriodEnd),
      billingType: 'prepaid',
      items: billItems, subtotal, taxAmount: totalTax, totalAmount, balanceDue: totalAmount,
      dueDate: dueDateObj, graceDate,
      notes, isAutoGenerated: true
    });
    await bill.save();
    customer.lastBillDate = new Date();
    customer.outstandingBalance += totalAmount;
    await customer.save();

    // Send invoice email (non-blocking)
    const emailResult = await sendInvoiceEmail(bill);

    res.status(201).json({ ...bill.toObject(), emailSent: emailResult.sent });
  } catch (error) {
    res.status(400).json({ error: error.message });
  }
});

// GET /api/bills/:id
router.get('/:id', auth, async (req, res) => {
  try {
    const bill = await Bill.findById(req.params.id).populate('customerId');
    if (!bill) return res.status(404).json({ error: 'Bill not found' });
    res.json(bill);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// GET /api/bills/:id/invoice - download PDF
router.get('/:id/invoice', auth, async (req, res) => {
  try {
    const bill = await Bill.findById(req.params.id);
    if (!bill) return res.status(404).json({ error: 'Bill not found' });
    const doc = new PDFDocument({ margin: 50 });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=Invoice-${bill.invoiceNumber.replace(/\//g, '-')}.pdf`);
    doc.pipe(res);

    doc.fontSize(24).font('Helvetica-Bold').text('RECORDRx', 50, 50);
    doc.fontSize(20).font('Helvetica-Bold').text('INVOICE', 450, 50, { align: 'right' });
    doc.fontSize(10).font('Helvetica').text(`#${bill.invoiceNumber}`, 450, 75, { align: 'right' });
    doc.moveTo(50, 100).lineTo(550, 100).stroke();

    doc.fontSize(10).font('Helvetica-Bold').text('Bill To:', 50, 120);
    doc.font('Helvetica').text(bill.customerName, 50, 135);
    doc.text(bill.customerAddress || '', 50, 150);
    doc.text(`Email: ${bill.customerEmail}`, 50, 180);
    if (bill.customerGstin) doc.text(`GSTIN: ${bill.customerGstin}`, 50, 195);

    doc.font('Helvetica-Bold').text('Invoice Details:', 350, 120);
    doc.font('Helvetica')
      .text(`Bill Number: ${bill.billNumber}`, 350, 135)
      .text(`Issue Date: ${bill.issueDate.toLocaleDateString('en-IN')}`, 350, 150)
      .text(`Due Date: ${bill.dueDate.toLocaleDateString('en-IN')}`, 350, 165)
      .text(`Status: ${bill.status.toUpperCase()}`, 350, 180);

    const tTop = 230;
    doc.font('Helvetica-Bold');
    doc.text('Description', 50, tTop); doc.text('Qty', 280, tTop); doc.text('Price', 330, tTop); doc.text('Tax', 420, tTop); doc.text('Amount', 480, tTop, { align: 'right' });
    doc.moveTo(50, tTop + 15).lineTo(550, tTop + 15).stroke();
    let y = tTop + 25;
    doc.font('Helvetica');
    for (const item of bill.items) {
      doc.text(item.description, 50, y, { width: 220 }); doc.text(String(item.quantity), 280, y);
      doc.text(`₹${item.unitPrice.toFixed(2)}`, 330, y); doc.text(`${item.taxRate}%`, 420, y);
      doc.text(`₹${(item.amount + item.taxAmount).toFixed(2)}`, 480, y, { align: 'right' });
      y += 20;
    }
    y += 20;
    doc.moveTo(350, y).lineTo(550, y).stroke(); y += 10;
    doc.text('Subtotal:', 350, y); doc.text(`₹${bill.subtotal.toFixed(2)}`, 480, y, { align: 'right' }); y += 18;
    doc.text('Tax (GST):', 350, y); doc.text(`₹${bill.taxAmount.toFixed(2)}`, 480, y, { align: 'right' }); y += 18;
    doc.moveTo(350, y).lineTo(550, y).stroke(); y += 10;
    doc.font('Helvetica-Bold');
    doc.text('Total:', 350, y); doc.text(`₹${bill.totalAmount.toFixed(2)}`, 480, y, { align: 'right' }); y += 18;
    doc.text('Balance Due:', 350, y); doc.text(`₹${bill.balanceDue.toFixed(2)}`, 480, y, { align: 'right' });

    doc.font('Helvetica').fontSize(9).text('Thank you for your business!', 50, 700, { align: 'center' });
    doc.end();
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

module.exports = router;
