const mongoose = require('mongoose');

const BillItemSchema = new mongoose.Schema({
  description: { type: String, required: true },
  quantity: { type: Number, default: 1 },
  unitPrice: { type: Number, required: true },
  amount: { type: Number, required: true },
  taxRate: { type: Number, default: 18 },
  taxAmount: { type: Number, default: 0 }
});

const BillSchema = new mongoose.Schema({
  billNumber: { type: String, required: true, unique: true },
  invoiceNumber: { type: String, required: true, unique: true },
  customerId: { type: mongoose.Schema.Types.ObjectId, ref: 'Customer', required: true },
  customerName: String,
  customerEmail: String,
  customerPhone: String,
  customerAddress: String,
  customerGstin: String,
  billingPeriodStart: { type: Date, required: true },
  billingPeriodEnd: { type: Date, required: true },
  items: [BillItemSchema],
  subtotal: { type: Number, required: true },
  taxAmount: { type: Number, default: 0 },
  discount: { type: Number, default: 0 },
  discountType: { type: String, enum: ['percentage', 'fixed'], default: 'fixed' },
  totalAmount: { type: Number, required: true },
  paidAmount: { type: Number, default: 0 },
  balanceDue: { type: Number, required: true },
  status: {
    type: String,
    enum: ['draft', 'pending', 'partial', 'paid', 'overdue', 'cancelled'],
    default: 'pending'
  },
  issueDate: { type: Date, default: Date.now },
  dueDate: { type: Date, required: true },
  paidDate: Date,
  notes: String,
  internalNotes: String,
  isAutoGenerated: { type: Boolean, default: false },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now }
});

BillSchema.statics.generateBillNumber = async function () {
  const date = new Date();
  const year = date.getFullYear().toString().slice(-2);
  const month = (date.getMonth() + 1).toString().padStart(2, '0');
  const prefix = `RRX${year}${month}`;
  const lastBill = await this.findOne({ billNumber: new RegExp(`^${prefix}`) }).sort({ billNumber: -1 });
  let seq = 1;
  if (lastBill) seq = parseInt(lastBill.billNumber.slice(-4)) + 1;
  return `${prefix}${seq.toString().padStart(4, '0')}`;
};

BillSchema.statics.generateInvoiceNumber = async function () {
  const year = new Date().getFullYear();
  const prefix = `INV/${year}/`;
  const last = await this.findOne({ invoiceNumber: new RegExp(`^${prefix}`) }).sort({ invoiceNumber: -1 });
  let seq = 1;
  if (last) seq = parseInt(last.invoiceNumber.split('/').pop()) + 1;
  return `${prefix}${seq.toString().padStart(5, '0')}`;
};

BillSchema.pre('save', function (next) {
  this.updatedAt = new Date();
  this.balanceDue = this.totalAmount - this.paidAmount;
  if (this.paidAmount >= this.totalAmount) {
    this.status = 'paid';
    if (!this.paidDate) this.paidDate = new Date();
  } else if (this.paidAmount > 0) {
    this.status = 'partial';
  } else if (this.dueDate < new Date() && this.status !== 'cancelled') {
    this.status = 'overdue';
  }
  next();
});

module.exports = mongoose.model('Bill', BillSchema);
